spring:
  datasource:
    url: jdbc:h2:mem:bookmanagerdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    root: info
springdoc:
  swagger-ui:
    operationsSorter: method
    path: "/swagger-ui.html"
    disable-swagger-default-url: true
